### ISSUE TITLE
cn get cli 国内环境依然是卡住了

### ISSUE THREAD

**Issue by cloudapex** [1467602180/cn_get_cli#1]
on windows

$ flutter --version
Flutter 2.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision adc687823a (8 weeks ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3

$ get init
  1) GetX Pattern (by Kauê)
  2) CLEAN (by Arktekko)
... 无限卡住了...

**Comment by hestudy** [comment]
确定调用的是cn_get_cli不，如果你安装了get_cli，那么cn_get_cli不应该重命名为get，这会引起冲突

**Comment by cloudapex** [comment]
thanks
